"""empty message

Revision ID: 24702428ae98
Revises: 9d6f42129539
Create Date: 2019-11-27 19:26:56.856729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '24702428ae98'
down_revision = '9d6f42129539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_ibfk_2', 'post', type_='foreignkey')
    op.drop_column('post', 'author_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('author_id', mysql.VARCHAR(length=100), nullable=False))
    op.create_foreign_key('post_ibfk_2', 'post', 'front_user', ['author_id'], ['id'])
    # ### end Alembic commands ###
