"""empty message

Revision ID: 4dedbba328c5
Revises: a83aa58272e6
Create Date: 2019-11-10 16:12:13.371262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dedbba328c5'
down_revision = 'a83aa58272e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banner', 'priority')
    # ### end Alembic commands ###
