"""empty message

Revision ID: 63eaa123a276
Revises: f952ddde11e5
Create Date: 2019-11-27 17:48:14.520438

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '63eaa123a276'
down_revision = 'f952ddde11e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_ibfk_2', 'post', type_='foreignkey')
    op.drop_column('post', 'author_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('author_id', mysql.VARCHAR(length=100), nullable=True))
    op.create_foreign_key('post_ibfk_2', 'post', 'front_user', ['author_id'], ['id'])
    # ### end Alembic commands ###
